project:
  type: default
  output-dir: output

format:
  pdf:
    documentclass: article
    papersize: a4
    geometry:
      - top=25mm
      - left=25mm
      - right=25mm
      - bottom=25mm
    toc: true
    toc-title: "Índice"
    number-sections: true
    colorlinks: true
    keep-tex: false

bibliography: referencias.bib
csl: ieee.csl